c=open('app/rewards.py',encoding='utf-8').read() 
c=c.replace('return 1.0','return 0.999') 
c=c.replace('return 0.0','return 0.001') 
open('app/rewards.py','w',encoding='utf-8').write(c) 
c=open('hospitalopsenv/app/rewards.py',encoding='utf-8').read() 
c=c.replace('return 1.0','return 0.999') 
c=c.replace('return 0.0','return 0.001') 
open('hospitalopsenv/app/rewards.py','w',encoding='utf-8').write(c) 
print('done') 
