a=open('inference.py',encoding='utf-8').read() 
b=open('_gi.py',encoding='utf-8').read() 
c=open('_hi.py',encoding='utf-8').read() 
print('inference Local==Git:',a==b,'Local==HF:',a==c) 
a=open('app/rewards.py',encoding='utf-8').read() 
b=open('_gr2.py',encoding='utf-8').read() 
c=open('_hr2.py',encoding='utf-8').read() 
print('rewards Local==Git:',a==b,'Local==HF:',a==c) 
a=open('app/graders.py',encoding='utf-8').read() 
b=open('_gg2.py',encoding='utf-8').read() 
c=open('_hg2.py',encoding='utf-8').read() 
print('graders Local==Git:',a==b,'Local==HF:',a==c) 
a=open('app_server.py',encoding='utf-8').read() 
b=open('_gs2.py',encoding='utf-8').read() 
c=open('_hs2.py',encoding='utf-8').read() 
print('app_server Local==Git:',a==b,'Local==HF:',a==c) 
a=open('openenv.yaml',encoding='utf-8').read() 
b=open('_goenv.py',encoding='utf-8').read() 
c=open('_hoenv.py',encoding='utf-8').read() 
print('openenv Local==Git:',a==b,'Local==HF:',a==c) 
