a=open('inference.py',encoding='utf-8').read() 
b=open('_gi.py',encoding='utf-8').read() 
c=open('_hi.py',encoding='utf-8').read() 
print('inference Local==Git:',a==b,'Local==HF:',a==c) 
a=open('app/rewards.py',encoding='utf-8').read() 
b=open('_gr.py',encoding='utf-8').read() 
c=open('_hr.py',encoding='utf-8').read() 
print('rewards Local==Git:',a==b,'Local==HF:',a==c) 
a=open('app/graders.py',encoding='utf-8').read() 
b=open('_gg.py',encoding='utf-8').read() 
c=open('_hg.py',encoding='utf-8').read() 
print('graders Local==Git:',a==b,'Local==HF:',a==c) 
a=open('app_server.py',encoding='utf-8').read() 
b=open('_gs.py',encoding='utf-8').read() 
c=open('_hs.py',encoding='utf-8').read() 
print('app_server Local==Git:',a==b,'Local==HF:',a==c) 
